require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CriterionsController do

  # This should return the minimal set of attributes required to create a valid
  # Criterion. As you add validations to Criterion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CriterionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "check_criterions" do
    it "should display the correct template" do
      criterions = Criterion.all
      get :check_criterions
      assigns(:criterions).should eq(criterions)
      response.should render_template('check_criterions')
    end
  end

  describe "GET index" do
    it "assigns all criterions as @criterions" do
      criterion = Criterion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:criterions).should eq([criterion])
    end
  end

  describe "GET show" do
    it "assigns the requested criterion as @criterion" do
      criterion = Criterion.create! valid_attributes
      get :show, {:id => criterion.to_param}, valid_session
      assigns(:criterion).should eq(criterion)
    end
  end

  describe "GET new" do
    it "assigns a new criterion as @criterion" do
      get :new, {}, valid_session
      assigns(:criterion).should be_a_new(Criterion)
    end
  end

  describe "GET edit" do
    it "assigns the requested criterion as @criterion" do
      criterion = Criterion.create! valid_attributes
      get :edit, {:id => criterion.to_param}, valid_session
      assigns(:criterion).should eq(criterion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Criterion" do
        expect {
          post :create, {:criterion => valid_attributes}, valid_session
        }.to change(Criterion, :count).by(1)
      end

      it "assigns a newly created criterion as @criterion" do
        post :create, {:criterion => valid_attributes}, valid_session
        assigns(:criterion).should be_a(Criterion)
        assigns(:criterion).should be_persisted
      end

      it "redirects to the criterion index page" do
        post :create, {:criterion => valid_attributes}, valid_session
        response.should redirect_to(criterions_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved criterion as @criterion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Criterion.any_instance.stub(:save).and_return(false)
        post :create, {:criterion => {}}, valid_session
        assigns(:criterion).should be_a_new(Criterion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Criterion.any_instance.stub(:save).and_return(false)
        post :create, {:criterion => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested criterion" do
        criterion = Criterion.create! valid_attributes
        # Assuming there are no other criterions in the database, this
        # specifies that the Criterion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Criterion.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => criterion.to_param, :criterion => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested criterion as @criterion" do
        criterion = Criterion.create! valid_attributes
        put :update, {:id => criterion.to_param, :criterion => valid_attributes}, valid_session
        assigns(:criterion).should eq(criterion)
      end

      it "redirects to the criterion index page" do
        criterion = Criterion.create! valid_attributes
        put :update, {:id => criterion.to_param, :criterion => valid_attributes}, valid_session
        response.should redirect_to(criterion_path)
      end
    end

    describe "with invalid params" do
      it "assigns the criterion as @criterion" do
        criterion = Criterion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Criterion.any_instance.stub(:save).and_return(false)
        put :update, {:id => criterion.to_param, :criterion => {}}, valid_session
        assigns(:criterion).should eq(criterion)
      end

      it "re-renders the 'edit' template" do
        criterion = Criterion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Criterion.any_instance.stub(:save).and_return(false)
        put :update, {:id => criterion.to_param, :criterion => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested criterion" do
      criterion = Criterion.create! valid_attributes
      expect {
        delete :destroy, {:id => criterion.to_param}, valid_session
      }.to change(Criterion, :count).by(-1)
    end

    it "redirects to the criterions list" do
      criterion = Criterion.create! valid_attributes
      delete :destroy, {:id => criterion.to_param}, valid_session
      response.should redirect_to(criterions_url)
    end
  end

end
